version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=Watcher
      - POSTGRES_DB=watcher
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

  server:
    build: ./src/server
    ports:
      - "8080:8080"
    restart: always
    networks:
      - backend
    depends_on:
      - db

#  client_web:
#    build: ./src/front/
#    ports:
#      - "8081:3000"
#    restart: always
#    networks:
#      - backend
#    depends_on:
#      - server
#    volumes:
#      - area:/app_web/build/apk

networks:
  backend:

volumes:
  area:
  db:
    driver: local